services:
  - type: web
    name: salary-management-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: salary
          property: connectionString

databases:
  - name: salary
